name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t Vishnuat/leechvs
    - name: login
      run: docker login -u omlz -p v75 && docker push Vishnuat/leechvs
