name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t Vishnuat/Leechwithvideotool
    - name: login
      run: docker login -u Vishnuat -p vishnuat2233 && docker push Vishnuat/Leechwithvideotool
